# Site settings
title: PadPrepper Chicago
email: brent@padprepper.com
description: > # this means to ignore newlines until "baseurl:"
  Chicago&#37;s top rated cleaning and painting service.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000.com" # the base hostname & protocol for your site
twitter_username: valebrent
github_username:  brentvale

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
